{% set name = "pyluach" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9063a25387cd7624276fd0656508bada08aa8a6f22e8db352844cd858e69012b

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.4
    - flit-core
  run:
    - python >=3.4

test:
  imports:
    - pyluach

about:
  home: https://github.com/simlist/pyluach
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Pyluach is a Python package for manipulating Hebrew dates, Gregorian-Hebrew calendar conversions, and other Jewish calendar related calculations.

extra:
  recipe-maintainers:
    - Matt-BF
