{% set name = "pyluach" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d7e42da6a384623542db3c9ec7b967b803af89318f6d95290ab14050ff3e8e47

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pyluach

about:
  home: https://github.com/simlist/pyluach
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Pyluach is a Python package for manipulating Hebrew dates, Gregorian-Hebrew calendar conversions, and other Jewish calendar related calculations.

extra:
  recipe-maintainers:
    - Matt-BF
