{% set name = "pyluach" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9cafb36d16941fc843d3a88de4b3d6c4e477b5874adb8564c37baac7e4ed58df

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - pyluach

about:
  home: https://github.com/simlist/pyluach
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Pyluach is a Python package for manipulating Hebrew dates, Gregorian-Hebrew calendar conversions, and other Jewish calendar related calculations.

extra:
  recipe-maintainers:
    - Matt-BF
