{% set name = "pyluach" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9cf95eaa600cc904d1adb015036ab135e0d732ca2a30253db92b676ee3415dea

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python>=3.4
  run:
    - python>=3.4

test:
  imports:
    - pyluach

about:
  home: https://github.com/simlist/pyluach
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Pyluach is a Python package for manipulating Hebrew dates, Gregorian-Hebrew calendar conversions, and other Jewish calendar related calculations.

extra:
  recipe-maintainers:
    - Matt-BF
