travis:
  secure:
    BINSTAR_TOKEN: HJ+HtMCsT63OpEJYggrPZKtYoDwrHq8FehxsbJX9oVUUHeYmXNM7MOVmauI+h1tB6bQbS+B3zHCtP3xX/+kpWpdHQ2AEZMVMUn+dqWRQTEx+5todg5cbUC3mbBj94+NZvxc0q5VZ/r6HFb++cbeMkz97ky/i8weKr1afjcdMfmxG/ZDRBcbwTesrF4DJfpcIxtzl0t4/UEQ3YCNEVkqY9FgghiauaBtJhutgeqzNrZl9KN0NSyKH5vHkLeZ8Zpw/nSIiulf01D+65BXFw0GBV/XrUFoCs8qpROwTQnnk+xw5OV7fhq+NhpnOG5snDy9raPo+tC5RO0yWS5zd8vttepUvJkiaXNmalydFClqmhvoEwPbcTwMbA2RUWxVvkXwIqpoLwafCMZ9S/6Cd8I/DPudMRu6xw7b4V6Gtz+BKILJMbhTrYmJoVXUXL5U/egatWkbU5T45KgLikd2WPMcc4okAJTuoMbJP7ktuyJi8lIm8b/5Wo1jS2mrh3hXqdbKotJNoF7uXXhdQ1FWZ2EGuAKFrmRRlDTW60E7YbA+PZzrlU5wxx54IL0lws6dpPxnZaestH3fcJQRAkbZjHHV2NSaFx8X6xsFbeoj9trLJf7EnYQFNJqCZ3kPPfPrRWiXXE0U1qdDzmWxA9qZhJ4rarShRdibk4IGO84ePamB783w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
